name = "Hydrogen"
uuid = "c74e06d2-87e8-4574-b8e9-4ec113e12dc0"
authors = ["Stefanos Carlstr√∂m <stefanos.carlstrom@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AngularMomentumAlgebra = "0bb1b1ac-0216-11e9-361b-bb110c659ce1"
AtomicLevels = "10933b4c-d60f-11e8-1fc6-bd9035a249a1"
EnergyExpressions = "f4b57a2e-27c7-11e9-0cb0-edd185b706f6"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
AngularMomentumAlgebra = "0.1, 0.2, 0.3"
AtomicLevels = "0.1"
EnergyExpressions = "0.1"
HypergeometricFunctions = "0.2, 0.3"
Polynomials = "1, 3"
PrettyTables = "2"
SpecialFunctions = "0.10, 2"
SpecialPolynomials = "0.1, 0.4"
WignerSymbols = "2.0.0"
julia = "1.10"

[extras]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PrettyTables", "Test"]
