[deps]
AtomicLevels = "10933b4c-d60f-11e8-1fc6-bd9035a249a1"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
